<a href="https://colab.research.google.com/github/kirat-anand-68/NEURAL_NETWORKS/blob/main/KRISH_NAIK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# braek down the neural network
# x-> input
# wx-> weights
# bx -> bias
# A-> Activation function
# y-> output.

# Z=W1.X + b1
# Z' =A(Z)
# Y=W2.Z' + b2

# loss function->
# backpropagation
# Optimizer

In [ ]:
# components of pytorch
# base class for defining custom models is : torch.nn.Module
# fuly connected or dense layers : torch.nn.Linear
# Activation function : torch.nn.ReLU
# Optimizer : torch.optim
# Loss : torch.nn.CrossEntropyLoss
# loads data in batches : torch.utils.data.DataLoader

In [ ]:
# #Ways to create a Neural Network
# Function : torch.nn.Function  more flexible, harder to interpret
# Sequential : nn.Sequential

In [1]:
# BUILDING A NEURAL NETWORK
import torch
import torch.nn as nn
import torch.optim as optim


In [2]:
# Functional API
class SimpleNN(nn.Module):

  def __init__(self, input_size,hidden_size, output_size):
    super(SimpleNN, self).__init__()

    self.fc1 = nn.Linear(input_size, hidden_size)

    self.relu = nn.ReLU()

    self.fc2 = nn.Linear(hidden_size, output_size)

  def forward(self, x):
    x=self.fc1(x)
    x=self.relu(x)
    x=self.fc2(x)
    return x

In [3]:
# sequential API
class SimpleNNSequential(nn.Module):

  def __init__(self, input_size,hidden_size, output_size):
    super(SimpleNNSequential, self).__init__()

    self.network=nn.Sequential(
        nn.Linear(input_size, hidden_size),
        nn.ReLU(),
        nn.Linear(hidden_size, output_size)

    )
  def forward(self, x):
    return self.network(x)

In [4]:
# training the neural network

model=SimpleNN(input_size=4, hidden_size=8, output_size=3)
print(model)

SimpleNN(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=8, out_features=3, bias=True)
)


In [6]:
X=torch.randn(10,4) # 10 samples

Y=torch.randint(0,3,(10,))

criteiro=nn.CrossEntropyLoss()
optimizer= optim.Adam(model.parameters(), lr=0.01)


In [7]:
print(X)

tensor([[ 0.4586, -0.0781,  0.6407,  0.3526],
        [-0.6280,  0.5917,  2.3621, -0.7249],
        [ 0.1585,  1.7706,  2.1152,  0.6860],
        [-0.5852,  0.0091, -1.2536, -0.3923],
        [-0.1382, -1.6360,  0.0842, -0.8433],
        [-0.5379, -0.6840,  1.5249,  0.6302],
        [ 0.6630, -0.5720,  0.3439, -1.0380],
        [ 0.6694,  1.5868, -0.8891, -0.5509],
        [ 0.1601,  0.4395,  0.9788, -0.4517],
        [ 1.1332, -1.4969,  1.5285, -0.0426]])


In [9]:
print(Y)

tensor([0, 2, 1, 0, 2, 2, 1, 2, 0, 1])


In [13]:
# training loop
epochs=50
for e in range(epochs):
  optimizer.zero_grad()
  outputs=model.forward(X)
  loss=criteiro(outputs, Y)
  loss.backward()
  optimizer.step()

  if (e+1) % 10 == 0:
    print(f"EPOCH [{e+1}]/50, Loss :{loss.item():.4f}")

EPOCH [10]/50, Loss :0.9235
EPOCH [20]/50, Loss :0.7813
EPOCH [30]/50, Loss :0.6381
EPOCH [40]/50, Loss :0.5027
EPOCH [50]/50, Loss :0.3884


In [ ]:
# REGRESSION MODEL USING THE PYTORCH
# Data gathering
# Data preprocessing
# Feature Engineering
# Model trained
# testing the model on the test set


In [14]:
import torch
import torch.nn as nn
import torch.optim as optim

# Model
model = nn.Sequential(
    nn.Linear(4, 8),
    nn.ReLU(),
    nn.Linear(8, 3)
)

# Dummy data
X = torch.randn(10, 4)
Y = torch.randint(0, 3, (10,))

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training
for epoch in range(50):

    # Forward pass
    outputs = model(X)

    # Calculate loss
    loss = criterion(outputs, Y)

    # Backpropagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print loss
    if (epoch + 1) % 10 == 0:
        print(f" Epoch {epoch+1}, Loss: {loss.item():.4f }")

Epoch 10, Loss: 0.8830
Epoch 20, Loss: 0.7523
Epoch 30, Loss: 0.6519
Epoch 40, Loss: 0.5608
Epoch 50, Loss: 0.5056


In [16]:
import pandas as pd

In [25]:
df=pd.read_csv("helloonsaurance.csv")

In [26]:
df.head()

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [28]:
df.isnull().sum()

,0
age,0
sex,0
bmi,0
children,0
smoker,0
region,0
charges,0


In [29]:
! pip install kaggle

In [ ]:
# path=kagglehub.dataset_download(" ")
# print(path)

In [30]:
df.describe()

,age,bmi,children,charges
count,1338.000000,1338.000000,1338.000000,1338.000000
mean,39.207025,30.663397,1.094918,13270.422265
std,14.049960,6.098187,1.205493,12110.011237
min,18.000000,15.960000,0.000000,1121.873900
25%,27.000000,26.296250,0.000000,4740.287150
50%,39.000000,30.400000,1.000000,9382.033000
75%,51.000000,34.693750,2.000000,16639.912515
max,64.000000,53.130000,5.000000,63770.428010


In [31]:
df["age"].value_counts()

,count
age,
18,69
19,68
46,29
52,29
50,29
47,29
48,29
51,29
45,29


In [32]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [33]:
# split the dataset before encoder
train_df, test_df = train_test_split(df,test_size=0.2, random_state=42)

In [34]:
# Encode categorical variables
label_encoder = {}
for col in ['sex','smoker','region']:
  le=LabelEncoder()
  train_df[col]=le.fit_transform(train_df[col])
  test_df[col]=le.transform(test_df[col])
  label_encoder[col] = le



In [36]:
# features and target
X_train=train_df.drop(columns=['charges'])
Y_train=train_df['charges']

X_test=test_df.drop(columns=['charges'])
Y_test=test_df['charges']

In [37]:
print(X_train)

      age  sex     bmi  children  smoker  region
560    46    0  19.950         2       0       1
1285   47    0  24.320         0       0       0
1142   52    0  24.860         0       0       2
969    39    0  34.320         5       0       2
486    54    0  21.470         3       0       1
...   ...  ...     ...       ...     ...     ...
1095   18    0  31.350         4       0       0
1130   39    0  23.870         5       0       2
1294   58    1  25.175         0       0       0
860    37    0  47.600         2       1       3
1126   55    1  29.900         0       0       3

[1070 rows x 6 columns]


In [38]:
print(Y_train)

560      9193.83850
1285     8534.67180
1142    27117.99378
969      8596.82780
486     12475.35130
           ...     
1095     4561.18850
1130     8582.30230
1294    11931.12525
860     46113.51100
1126    10214.63600
Name: charges, Length: 1070, dtype: float64


In [39]:
# Normalize features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [40]:
print(X_train)

[[ 0.47222651 -1.0246016  -1.75652513  0.73433626 -0.50874702 -0.45611589]
 [ 0.54331294 -1.0246016  -1.03308239 -0.91119211 -0.50874702 -1.35325561]
 [ 0.8987451  -1.0246016  -0.94368672 -0.91119211 -0.50874702  0.44102382]
 ...
 [ 1.3252637   0.97598911 -0.89153925 -0.91119211 -0.50874702 -1.35325561]
 [-0.16755139 -1.0246016   2.82086429  0.73433626  1.96561348  1.33816354]
 [ 1.1120044   0.97598911 -0.10932713 -0.91119211 -0.50874702  1.33816354]]


In [41]:
print(Y_train)

560      9193.83850
1285     8534.67180
1142    27117.99378
969      8596.82780
486     12475.35130
           ...     
1095     4561.18850
1130     8582.30230
1294    11931.12525
860     46113.51100
1126    10214.63600
Name: charges, Length: 1070, dtype: float64


In [43]:
# convert to tensors
X_train_tensor=torch.tensor(X_train, dtype=torch.float32)
Y_train_tensor=torch.tensor(Y_train.values, dtype=torch.float32).view(-1,1)
X_test_tensor=torch.tensor(X_test, dtype=torch.float32)
Y_test_tensor=torch.tensor(Y_test.values, dtype=torch.float32).view(-1,1)


In [45]:
print(Y_train_tensor)

tensor([[ 9193.8389],
        [ 8534.6719],
        [27117.9941],
        ...,
        [11931.1250],
        [46113.5117],
        [10214.6357]])


In [46]:
print(X_test_tensor)

tensor([[ 0.4586, -0.9562, -0.9372,  0.8225, -0.5023, -1.4541],
        [-0.1871, -0.9562, -0.1675, -0.8996, -0.5023, -0.5128],
        [ 1.8218, -0.9562, -0.6655, -0.8996,  1.9907, -0.5128],
        ...,
        [-0.0436,  1.0458, -0.4844, -0.0386, -0.5023, -1.4541],
        [ 1.1043, -0.9562,  2.5949, -0.8996,  1.9907,  0.4285],
        [ 0.8891, -0.9562,  0.4965, -0.0386, -0.5023,  1.3698]])


In [50]:
# Define Neural Network Model

class SimpleNNRegressionModel(nn.Module):
  def __init__(self, input_dim):
    super(SimpleNNRegressionModel, self).__init__()
    self.network = nn.Sequential(
        nn.Linear(input_dim, 64),
        nn.ReLU(),
        nn.Linear(64, 128),
        nn.ReLU(),
        nn.Linear(128, 1)
    )

  def forward(self, x):
    return self.network(x)

In [48]:
X_train_tensor.shape

torch.Size([1070, 6])

In [52]:
input_dim = X_train_tensor.shape[1]

model = SimpleNNRegressionModel(input_dim)

In [53]:
print(model)

SimpleNNRegressionModel(
  (network): Sequential(
    (0): Linear(in_features=6, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=128, bias=True)
    (3): ReLU()
    (4): Linear(in_features=128, out_features=1, bias=True)
  )
)


In [59]:
# loss and optiizer

criterion = nn.MSELoss()

optimizer = optim.Adam(model.parameters(), lr=0.01)

epochs = 30000

for epoch in range(epochs):

    model.train()

    optimizer.zero_grad()

    prediction = model(X_train_tensor)

    loss = criterion(prediction, Y_train_tensor)

    loss.backward()

    optimizer.step()

    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.6f}")


Epoch [100/30000], Loss: 1427134.000000
Epoch [200/30000], Loss: 1422443.375000
Epoch [300/30000], Loss: 1421724.750000
Epoch [400/30000], Loss: 1421169.875000
Epoch [500/30000], Loss: 1420535.250000
Epoch [600/30000], Loss: 1420076.125000
Epoch [700/30000], Loss: 1419175.000000
Epoch [800/30000], Loss: 1418725.250000
Epoch [900/30000], Loss: 1417786.875000
Epoch [1000/30000], Loss: 1416907.500000
Epoch [1100/30000], Loss: 1416418.375000
Epoch [1200/30000], Loss: 1415314.375000
Epoch [1300/30000], Loss: 1414091.125000
Epoch [1400/30000], Loss: 1413096.125000
Epoch [1500/30000], Loss: 1411826.375000
Epoch [1600/30000], Loss: 1411688.375000
Epoch [1700/30000], Loss: 1413825.125000
Epoch [1800/30000], Loss: 1427042.750000
Epoch [1900/30000], Loss: 1412491.375000
Epoch [2000/30000], Loss: 1454151.625000
Epoch [2100/30000], Loss: 1458984.000000
Epoch [2200/30000], Loss: 1406733.000000
Epoch [2300/30000], Loss: 1430993.375000
Epoch [2400/30000], Loss: 1428673.750000
Epoch [2500/30000], Loss:

In [61]:
model.eval()
y_pred=model(X_test_tensor).detach().numpy()

In [62]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

Y_test_numpy = Y_test_tensor.numpy()
# calculate metrics\
mse=mean_squared_error(Y_test_numpy, y_pred)
rmse = mse **0.5
mae=mean_absolute_error(Y_test_numpy, y_pred)
r2=r2_score(Y_test_numpy, y_pred)

print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"MAE: {mae}")
print(f"R2_SCORE: {r2}")

MSE: 78849864.0
RMSE: 8879.74459092152
MAE: 6113.41064453125
R2_SCORE: 0.49210619926452637


In [70]:
def predict_charges(age, sex, bmi, children, smoker,region):
  input_data=pd.DataFrame([[age, sex, bmi, children, smoker, region]],
               columns=['age','sex','bmi','children','smoker','region'])

  for col in ['sex','smoker','region']:
    input_data[col]=label_encoder[col].transform(input_data[col])
  input_data=scaler.transform(input_data)
  input_tensor=torch.tensor(input_data, dtype= torch.float32)
  predicted_charge=model(input_tensor).item()
  return predicted_charge


In [73]:
predicted=predict_charges(62,'female',26.29,0,'yes','southeast')

In [74]:
predicted

28447.12109375